apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html-config
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>GitOps NGINX App</title>
    </head>
    <body>
        <h1>¡Bienvenido a la aplicación NGINX desplegada con GitOps!</h1>
    </body>
    </html>
